### ISSUE TITLE
TypeError: this._editor.setValue is not a function

### ISSUE THREAD

**Issue by vu-bui** [Teradata/covalent-code-editor#56]
I encountered this error after upgrading to 2.0.0. Reverting back to 2.0.0-rc.2 works for me.
```
ERROR TypeError: this._editor.setValue is not a function
    at TdCodeEditorComponent.set [as value] (covalent-code-editor.js:124)
    at TdCodeEditorComponent.push../node_modules/@covalent/code-editor/fesm5/covalent-code-editor.js.TdCodeEditorComponent.writeValue (covalent-code-editor.js:152)
    at setUpControl (forms.js:2007)
    at NgModel../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpStandalone (forms.js:4732)
    at NgModel../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpControl (forms.js:4719)
    at NgModel../node_modules/@angular/forms/fesm5/forms.js.NgModel.ngOnChanges (forms.js:4649)
    at checkAndUpdateDirectiveInline (core.js:20661)
    at checkAndUpdateNodeInline (core.js:21929)
    at checkAndUpdateNode (core.js:21891)
    at debugCheckAndUpdateNode (core.js:22525)
```

In my code:
```
<td-code-editor language="javascript" [editorOptions]="{ lineNumbersMinChars: 3, minimap: { enabled: false } }" [(ngModel)]="action.code" fxFlex="grow"></td-code-editor>
```

Thanks,

**Comment by Pranjalich** [comment]
Hello i am having the same problem in Ionic 4. 

`ERROR TypeError: this._editor.setValue is not a function
    at TdCodeEditorComponent.set [as value] (covalent-code-editor.js:124)
    at TdCodeEditorComponent.push../node_modules/@covalent/code-editor/fesm5/covalent-code-editor.js.TdCodeEditorComponent.writeValue (covalent-code-editor.js:152)
    at setUpControl (forms.js:2005)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpStandalone (forms.js:4533)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpControl (forms.js:4520)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel.ngOnChanges (forms.js:4480)
    at checkAndUpdateDirectiveInline (core.js:18533)
    at checkAndUpdateNodeInline (core.js:19801)
    at checkAndUpdateNode (core.js:19763)
    at debugCheckAndUpdateNode (core.js:20397)`

**Comment by Pranjalich** [comment]
The problem is with ngModel. 

`<td-code-editor #monaco style="height: 600px" [language]="'html'" [editorOptions]="options" [(value)]="code" (change)="codeChange()"> </td-code-editor>
`
works fine. But the same doesn't work with ngModel

`<td-code-editor #monaco style="height: 600px" [language]="'html'" [editorOptions]="options" [(ngModel)]="code" (change)="codeChange()"> </td-code-editor>`

**Comment by viccsjain** [comment]
I have raised PR to fix this issue:
https://github.com/Teradata/covalent-code-editor/pull/57

**Comment by jeremysmartt** [comment]
A patch release has been released:
https://www.npmjs.com/package/@covalent/code-editor/v/2.0.2
